# Generated by Django 6.0.6 on 2026-08-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='membership_plan',
            field=models.CharField(choices=[('Free', 'Free'), ('Pro', 'Pro'), ('Elite', 'Elite')], default='Free', max_length=20),
        ),
    ]
